In [15]:
import numpy as np

1)
а) $A$ — матрица $4*2$, $B$ — матрица $4*2$; $AB$ и $BA$ - неопределены (недопустимая операция),
      
 б) $A$ — матрица $2*5$, $B$ — матрица $5*3$; $AB$ - $2*3$; $BA$ - неопределена,
      
 в) $A$ — матрица $8*3$, $B$ — матрица $3*8$; $AB$ - $8*8$;  $BA$ - $3*3$,
    
 г) $A$ — квадратная матрица $4*4$, $B$ — квадратная матрица $4*4$. $AB$ - $4*4$; $BA$ - $4*4$
  

In [16]:
#a)
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
B = np.array([[9, 10], [1, 2], [2, 4], [5, 7]])
print('a)')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')


a)


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [17]:
A = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
B = np.array([[1, 0, 3], [2, 2, 4], [10, 5, 1], [5, 10, 8], [10, 5, 2]])
print('б)')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

б)
Матрица AB
[[ 77  62  38]
 [217 172 128]]


ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8], [9, 10, 11], [10, 9, 8], [7, 6, 5], [4, 3, 2], [1, 0, 0]])
B = np.array([[0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7]])
print('в)')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

в)
Матрица AB
[[  0   6  12  18  24  30  36  42]
 [  0  15  30  45  60  75  90 105]
 [  0  21  42  63  84 105 126 147]
 [  0  30  60  90 120 150 180 210]
 [  0  27  54  81 108 135 162 189]
 [  0  18  36  54  72  90 108 126]
 [  0   9  18  27  36  45  54  63]
 [  0   1   2   3   4   5   6   7]]
Матрица BA
[[149 133 124]
 [149 133 124]
 [149 133 124]]


In [19]:
A = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
B = np.array([[5, 6, 7, 8], [5, 6, 7, 8], [5, 6, 7, 8], [5, 6, 7, 8]])
print('г)')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

г)
Матрица AB
[[50 60 70 80]
 [50 60 70 80]
 [50 60 70 80]
 [50 60 70 80]]
Матрица BA
[[ 26  52  78 104]
 [ 26  52  78 104]
 [ 26  52  78 104]
 [ 26  52  78 104]]


2) Найти сумму и произведение матриц A и B

In [20]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Сумма матриц A + B\n{A + B}')
print(f'Произведение AB\n{np.dot(A, B)}')

Сумма матриц A + B
[[ 5 -3]
 [ 3  5]]
Произведение AB
[[  4 -11]
 [ 12  -3]]


3)Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц  A, B, C

In [21]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2 ,-1]])
C = np.array([[2 ,-4],[1, 1]])

b = -2*B

print(f"Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = \n{3*A + b + 4*C}\n")

Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = 
[[ 11  -5]
 [  9 -12]]



4)Дана матрица A. Вычислить AA^T и  A^T*A

In [22]:
A = np.array([[4, 1], [5, -2], [2, 3]])
AT = A.T
print(f'Матрица AA^T\n{np.dot(A, AT)}')
print(f'Матрица A^T*A\n{np.dot(AT, A)}')

Матрица AA^T
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A^T*A
[[45  0]
 [ 0 14]]


5)Вычислить определитель:

In [23]:
A = np.array([[4, 1], [5, -2]])
print('а)')
print(f'Определитель:\n sin^2(x)+cos^2(x) = 1')

а)
Определитель:
 sin^2(x)+cos^2(x) = 1


In [25]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print('б) т.к. матрица имеет ступенчатый вид перемножим диаганальные элементы и сравним со встроенной функцией')
print(f'Определитель:\n 4 * 5 * 9 = 180')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

б) т.к. матрица имеет ступенчатый вид перемножим диаганальные элементы и сравним со встроенной функцией
Определитель:
 4 * 5 * 9 = 180
Определитель:
180


In [26]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('в)')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

в)
Определитель:
-0


6)Доказать, что матрица вырожденная

In [29]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
if(np.linalg.det(A)==0):
    print(f'Так как определитель ноль -> матрица вырожденная')
else:
     print(f'Так как определитель не ноль -> матрица не вырожденная')

Так как определитель ноль -> матрица вырожденная


7)Найти ранг матрицы

In [30]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Ранг матрицы: {np.linalg.matrix_rank(A)}')

Ранг матрицы: 2
