1)Решить систему уравнений методом Гаусса(см. фотографию)

2)Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

In [2]:
import numpy as np
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
A_ = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))
print("Ранг расширенной матрицы равен рангу матрицы коэффициентов и равен количеству неизвестных, значит система совместна с единственным решением")

Ранг матрицы коэфициентов: 3
Ранг расширенной матрицы: 3
Ранг расширенной матрицы равен рангу матрицы коэффициентов и равен количеству неизвестных, значит система совместна с единственным решением


In [3]:
A = np.array([[2,-4,-6],[1,-2,3],[3,-6,9]])
print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
A_ = np.array([[2,-4,-6,1],[1,-2,3,-2],[3,-6,9,5]])
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))
print("Ранг расширенной матрицы больше ранга матрицы коэффициентов, значит система несовместна")

Ранг матрицы коэфициентов: 2
Ранг расширенной матрицы: 3
Ранг расширенной матрицы больше ранга матрицы коэффициентов, значит система несовместна


In [4]:
A = np.array([[1,2,5],[3,1,-8]])
print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
A_ = np.array([[1,2,5,4],[3,1,-8,-2]])
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))
print("Ранг расширенной матрицы равен рангу матрицы коэффициентов, но меньше числа неизвестных, значит система совместна и имеет бесконечно много решений")

Ранг матрицы коэфициентов: 2
Ранг расширенной матрицы: 2
Ранг расширенной матрицы равен рангу матрицы коэффициентов, но меньше числа неизвестных, значит система совместна и имеет бесконечно много решений


3)Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

In [5]:
import numpy as np
A = np.array([[1,3,-2,4],[0,5,0,1],[0,0,3,0],[0,0,0,2]])

A_ = np.array([[1,3,-2,4,3],[0,5,0,1,2],[0,0,3,0,4],[0,0,0,2,1]])

print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))
print("Согласно Теореме Кронекера — Капелли система совместна и имеет одно решение так как ранг матрицы коэфициентов и расширеной матрицы совпадают и равны числу неизвестных")

Ранг матрицы коэфициентов: 4
Ранг расширенной матрицы: 4
Согласно Теореме Кронекера — Капелли система совместна и имеет одно решение так как ранг матрицы коэфициентов и расширеной матрицы совпадают и равны числу неизвестных


4)Дана система линейных уравнений, заданная расширенной матрицей.Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной(см. фотографию).

5)Решить систему уравнений методом Крамера:

In [6]:
A = np.array([[1,-2],[3,-4]])
A1 = np.array([[1,-2],[7,-4]])
A2 = np.array([[1,1],[3,7]])
print(f'а)')
print(f'х1 = {np.linalg.det(A1)/np.linalg.det(A):.0f}')
print(f'х2 = {np.linalg.det(A2)/np.linalg.det(A):.0f}')


а)
х1 = 5
х2 = 2


6)Решить систему уравнений методом Крамера:

In [8]:
from scipy.linalg import lu
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = lu(A)
B = P.dot(L).dot(U)
print(B)
print('L-матрица:')
print(L)


[[ 3.         26.         30.        ]
 [ 0.         -8.33333333 -8.        ]
 [ 0.          0.          0.4       ]]
[[ 1.  2.  4.]
 [ 2.  9. 12.]
 [ 3. 26. 30.]]
L-матрица:
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]


7)Решить систему линейных уравнений методом $LU$-разложения

In [9]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
P, L, U = lu(A)
print(L)

[[ 1.          0.          0.        ]
 [ 0.81818182  1.          0.        ]
 [ 0.18181818 -0.12        1.        ]]


Решим полученную систему c L

In [10]:
print(U)

[[11.          7.          5.        ]
 [ 0.          2.27272727 -0.09090909]
 [ 0.          0.          2.08      ]]


Решим полученную систему c U

8)Решить систему линейных уравнений методом Холецкого


In [11]:
from numpy.linalg import cholesky
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
L = cholesky(A)
LT = L.T
print(L)

[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]


Решим систему $Ly=b:$ и  $L^{T}x=y:$ в фото Ly=b.jpg и Ly=b.jpg соответственно

Найти с помощью NumPy SVD для матрицы

In [14]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
U, s, VT = np.linalg.svd(A)
V = VT.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')
print(f'Матрица V:\n{V}')


Матрица D:
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
Матрица U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]
Матрица V:
[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]
